# Generated by Django 4.0.3 on 2022-08-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_uploadprescription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadprescription',
            name='status',
        ),
    ]
